### ISSUE TITLE
How to open project in Eclipse?

### ISSUE THREAD

**Issue by DarthYuber** [RyanGrieb/OpenCiv#61]
I did what the readme says but it did not work?

> ## How do I build and run this?
* Install [Java 11](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html) or higher. NOTE: OpenJDK has problems (at least for me on linux)
* Install [GIT](https://git-scm.com/downloads)
* Run -> ```git clone https://github.com/rhin123/OpenCiv.git```
* Open Eclipse or any other java editor, and ```import grade project``` (Eclipse is recommended, haven't tested on other IDEs)
* To get the game running you would run the OpenCiv-lwjgl3 ```Lwjgl3Launcher.java``` class & the OpenCiv-server ```Server.jar``` To start the Client & Server
* 

What folder do I need to "import grade project"?
I tried many and always get error messages.

**Comment by rhin123** [comment]
What error messages are you getting? The folder you import is the ```OpenCiv``` folder. Don't import the sub-folders.
