### ISSUE TITLE
OpenCiv: Create standard development environment

### ISSUE THREAD

**Issue by RyanGrieb** [RyanGrieb/OpenCiv#65]
As it stands, it's hard for new users to setup this projects development environment. It all comes down to their version of JDK, what IDE they're using, and other variables. 

[willpewitt](https://github.com/willpewitt) mentions in #64 that we should look into using Docker. After spending the whole day trying to get it working I'm going to give up for now since I have no idea what I'm doing with that.

If anyone has any suggestions to make this project more easy to contribute to, please let me know.

**Comment by rhin123** [comment]
The main reason we're having problems in the first place is Gradle seems to break depending on it's version & the current version of java. I'm honestly just considering dropping Gradle in favor of maven, or even XML. Where I don't have to worry above things breaking every java update.
