### ISSUE TITLE
Chat: Implement whisper command

### ISSUE THREAD

**Issue by RyanGrieb** [RyanGrieb/OpenCiv#66]
We would simply add a WhisperCommand class & send the player the message through  ```sendServerMessage(...)```.

We could also look into changing the chat color for whispers, but that is more advanced.

**Comment by IanWorley** [comment]
This might be fun to work on

**Comment by rhin123** [comment]
> This might be fun to work on

Go for it man, let me know if you have any questions.

**Comment by IanWorley** [comment]
Hey there bump this issue I have gotten a little busy recently and I am worried I do not have time to work on the issue. @rhin123

**Comment by rhin123** [comment]
> Hey there bump this issue I have gotten a little busy recently and I am worried I do not have time to work on the issue. @rhin123

That's okay. Maybe next time.
