### ISSUE TITLE
Chat: Implement /help command

### ISSUE THREAD

**Issue by RyanGrieb** [RyanGrieb/OpenCiv#68]
Currently there is no way for the player to get a list of commands from chat, the implementation of ```/help``` would fix this. For the command, the server would just ```sendServerMessage(...)``` a list of our commands to the player.

**Comment by Sidahmed-ben** [comment]
hello @rhin123, the issue interests me, can you assing  it to me please. Thank you !

>

**Comment by rhin123** [comment]
> hello @rhin123, the issue interests me, can you assing it to me please. Thank you !

Awesome, I will. Let me know if you have any questions at all, I'm happy to help.
